# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-2020-LAPTOP-80SBIOPI/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {
    d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/processing_system7_bfm_v2_0/adcdcea3/hdl
    d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0
    d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog
  } {
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/ad955ff5/hdl/verilog/processing_system7_v5_5_aw_atc.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/ad955ff5/hdl/verilog/processing_system7_v5_5_b_atc.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/ad955ff5/hdl/verilog/processing_system7_v5_5_w_atc.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/ad955ff5/hdl/verilog/processing_system7_v5_5_atc.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/ad955ff5/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/synth/design_1_processing_system7_0_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/uart_lite_tx_v1_0/7b2b1654/src/uart_tx.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/uart_lite_tx_v1_0/7b2b1654/hdl/UART_LITE_TX_v1_0_uart_tx.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/uart_lite_tx_v1_0/7b2b1654/hdl/UART_LITE_TX_v1_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_UART_LITE_TX_0_2/synth/design_1_UART_LITE_TX_0_2.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/spi_mosi_v1_0/fc3b8355/src/spi_mosi.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/spi_mosi_v1_0/fc3b8355/hdl/SPI_MOSI_v1_0_SPI_MOSI.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/spi_mosi_v1_0/fc3b8355/hdl/SPI_MOSI_v1_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_SPI_MOSI_0_0/synth/design_1_SPI_MOSI_0_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_and.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_or.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_mux.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_register_slice_v2_1/03a8e0ba/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_register_slice_v2_1/03a8e0ba/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_addr_arbiter_sasd.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_addr_arbiter.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_addr_decoder.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_arbiter_resp.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_crossbar_sasd.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_crossbar.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_decerr_slave.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_si_transactor.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_splitter.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_wdata_mux.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_wdata_router.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_axi_crossbar.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/synth/design_1_xbar_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/dht11_ip_v1_0/c8050bd9/src/DHT11.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/dht11_ip_v1_0/c8050bd9/hdl/DHT11_IP_v1_0_S00_AXI.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/dht11_ip_v1_0/c8050bd9/hdl/DHT11_IP_v1_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_DHT11_IP_0_0/synth/design_1_DHT11_IP_0_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/asr_rcv_v1_0/33509239/src/asr_rcv.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/asr_rcv_v1_0/33509239/hdl/ASR_rcv_v1_0_S00_AXI.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/asr_rcv_v1_0/33509239/hdl/ASR_rcv_v1_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_ASR_rcv_0_0/synth/design_1_ASR_rcv_0_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/uart_xfh_v1_0/1381927c/src/UART_xfh.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/uart_xfh_v1_0/1381927c/hdl/UART_xfh_v1_0_S00_AXI.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/uart_xfh_v1_0/1381927c/hdl/UART_xfh_v1_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_UART_xfh_0_0/synth/design_1_UART_xfh_0_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/jiaquan_v1_0/eb005c8c/src/jiaquan.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/jiaquan_v1_0/eb005c8c/hdl/jiaquan_v1_0_S00_AXI.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/jiaquan_v1_0/eb005c8c/hdl/jiaquan_v1_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_jiaquan_0_0/synth/design_1_jiaquan_0_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_UART_xfh_0_1/synth/design_1_UART_xfh_0_1.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/pm_v1_0/43476f31/hdl/pm.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/pm_v1_0/43476f31/hdl/PM_v1_0_S00_AXI.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/pm_v1_0/43476f31/hdl/PM_v1_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_PM_0_0/synth/design_1_PM_0_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_UART_xfh_1_0/synth/design_1_UART_xfh_1_0.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/synth/design_1_auto_pc_0.v
      D:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/hdl/design_1.v
      D:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
    }
      rt::read_vhdl -lib lib_cdc_v1_0 d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/lib_cdc_v1_0/ea79928f/hdl/src/vhdl/cdc_sync.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0 {
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/upcnt_n.vhd
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/sequence.vhd
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/lpf.vhd
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/proc_sys_reset.vhd
    }
      rt::read_vhdl -lib xil_defaultlib d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/synth/design_1_rst_processing_system7_0_100M_0.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_2 {
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/blk_mem_gen_v8_2/7b054ed9/hdl/blk_mem_gen_v8_2_vhsyn_rfs.vhd
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/blk_mem_gen_v8_2/7b054ed9/hdl/blk_mem_gen_v8_2.vhd
    }
      rt::read_vhdl -lib fifo_generator_v12_0 {
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/fifo_generator_v12_0/15467f24/hdl/fifo_generator_v12_0_vhsyn_rfs.vhd
      d:/study/Grade3/hardware/REAL/TTS/TTS_IP_LITE/project_1/project_1.srcs/sources_1/ipshared/xilinx.com/fifo_generator_v12_0/15467f24/hdl/fifo_generator_v12_0.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-2020-LAPTOP-80SBIOPI/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
