# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/study/Grade3/hardware/REAL/IP/ip_repo/UART_LITE_TX/edit_UART_LITE_TX_v1_0.cache/wt [current_project]
set_property parent.project_path D:/study/Grade3/hardware/REAL/IP/ip_repo/UART_LITE_TX/edit_UART_LITE_TX_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/study/Grade3/hardware/REAL/IP/ip_repo/UART_LITE_TX/UART_LITE_TX_1.0
  d:/study/Grade3/hardware/REAL/IP/ip_repo/UART_STREAM_TX/UART_STREAM_TX_1.0
  d:/study/Grade3/hardware/REAL/IP/ip_repo/SPI_MOSI/SPI_MOSI_1.0
} [current_project]
read_verilog -library xil_defaultlib {
  D:/study/Grade3/hardware/REAL/IP/ip_repo/UART_LITE_TX/edit_UART_LITE_TX_v1_0.srcs/sources_1/imports/Desktop/uart_tx.v
  D:/study/Grade3/hardware/REAL/IP/ip_repo/UART_LITE_TX/uart_lite_tx_1.0/hdl/UART_LITE_TX_v1_0_uart_tx.v
  D:/study/Grade3/hardware/REAL/IP/ip_repo/UART_LITE_TX/uart_lite_tx_1.0/hdl/UART_LITE_TX_v1_0.v
}
synth_design -top UART_LITE_TX_v1_0 -part xc7z020clg484-1
write_checkpoint -noxdef UART_LITE_TX_v1_0.dcp
catch { report_utilization -file UART_LITE_TX_v1_0_utilization_synth.rpt -pb UART_LITE_TX_v1_0_utilization_synth.pb }
