# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir d:/study/grade3/hardware/real/ip/ip_repo/spi_mosi/edit_SPI_MOSI_v1_0.cache/wt [current_project]
set_property parent.project_path d:/study/grade3/hardware/real/ip/ip_repo/spi_mosi/edit_SPI_MOSI_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/study/Grade3/hardware/REAL/IP/ip_repo/SPI_MOSI/SPI_MOSI_1.0
  d:/study/Grade3/hardware/REAL/IP/ip_repo/ASR_RCV/ASR_rcv_1.0
  d:/study/Grade3/hardware/REAL/IP/ip_repo/UART_LITE_TX/UART_LITE_TX_1.0
  d:/study/Grade3/hardware/REAL/IP/ip_repo/UART_STREAM_TX/UART_STREAM_TX_1.0
} [current_project]
read_verilog -library xil_defaultlib {
  D:/study/Grade3/hardware/REAL/IP/ip_repo/SPI_MOSI/SPI_MOSI_1.0/src/spi_mosi.v
  d:/study/grade3/hardware/real/ip/ip_repo/spi_mosi/spi_mosi_1.0/hdl/SPI_MOSI_v1_0_SPI_MOSI.v
  d:/study/grade3/hardware/real/ip/ip_repo/spi_mosi/spi_mosi_1.0/hdl/SPI_MOSI_v1_0.v
}
synth_design -top SPI_MOSI_v1_0 -part xc7z020clg484-1
write_checkpoint -noxdef SPI_MOSI_v1_0.dcp
catch { report_utilization -file SPI_MOSI_v1_0_utilization_synth.rpt -pb SPI_MOSI_v1_0_utilization_synth.pb }
